shopping_center = ("Галерея", "Санкт-Петербург", "Лиговский пр., 30", ["H&M", "Zara"])
list_id_before = id(shopping_center[-1])
print(id(list_id_before))
shopping_center[-1].append("Uniqlo")
list_id_after = id(shopping_center[-1])
print(id(list_id_after))
print(id(list_id_before) is id(list_id_after))
